server:
  port: 7080
  servlet:
    context-path: /jsp
mybatis:
  mapper-locations: classpath:mapper/*xml
logging:
  level:
    root: INFO
spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.93.30.98:3306/jsp?useSSL=false
    username: root
    password: mn814561293
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      auto-commit: true
      minimum-idle: 1
      maximum-pool-size: 15
      idle-timeout: 30000
      pool-name: jsp-cp
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  redis:
    database: 1
    host: 47.93.30.98
    password: mn814561293
    port: 6379
    timeout: 5000
    jedis:
      pool:
        min-idle: 0
  #jackson日期解析格式
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  #编码格式encoding
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  messages:
    encoding: UTF-8
  #配置改变内容不需要重启的路径
  devtools:
    restart:
      exclude: static/**

#定时调度
reload:
  timer:
    fixedRate: 60000
plan:
  generate:
    timer:
      corn: 0 0/1 * ? * *