mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml

#项目接口请求前缀,如果是部署在tomcat下，必须配置该项，且必须与项目名称一致
server:
  port: 7080
  servlet:
    context-path: /jsp

spring:
  #jackson日期解析格式
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  #编码格式encoding
  http:
    encoding:
      charset: UTF-8
      enabled: UTF-8
      force: true
  messages:
    encoding: UTF-8
  #配置jsp
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  #配置改变内容不需要重启的路径
  devtools:
    restart:
      exclude: static/**
